export BROKER_USERNAME="broker"
export BROKER_PASSWORD="broker"
export ONTAP_USER="admin"
export ONTAP_PASSWORD="P@ssw0rd"
export ONTAP_URL="https://172.16.3.100"
export ONTAP_SKIP_SSL_CHECK="true"
export ONTAP_SVM_NAME="svm0"
export CIFS_HOSTNAME="172.16.3.102"
export TRUSTED_SSH_KEY="ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFeijwHmvJ2hR3izMv8KOAb+h8JqA92/SOGQvcwmUI3FBf+SYW1eWt44tCAOoKeJZsWKPnVP/aEtc4EKiU3jzXc="
export DOCSURL="http://localhost"